import classNames from 'classnames';
import type { Metadata } from 'next';
import { Baloo_2 } from 'next/font/google';

import { Layout } from '@/components/layouts/layout';
import { Providers } from '@/app/providers';

import { AppChildren } from '@/types';

import '@/global/styles.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fonts = Baloo_2({
  weight: ['500', '400', '600', '700', '800'],
  subsets: ['latin'],
});

const RootLayout = ({ children }: Readonly<AppChildren>) => {
  return (
    <html lang="en" className={classNames('dark', fonts.className)}>
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
